"""initial commit

Revision ID: 07087dc0dd28
Revises: 
Create Date: 2026-03-24 10:57:19.190198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07087dc0dd28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('User_id', sa.UUID(), nullable=False),
    sa.Column('Full_Name', sa.String(), nullable=False),
    sa.Column('Created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('User_id'),
    sa.UniqueConstraint('Full_Name')
    )
    op.create_index('ix_Full_Name', 'users', ['Full_Name'], unique=False)
    op.create_table('sessions',
    sa.Column('Session_id', sa.UUID(), nullable=False),
    sa.Column('Created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('End_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Chat_Summary', sa.String(), nullable=True),
    sa.Column('Session_User_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['Session_User_id'], ['users.User_id'], ),
    sa.PrimaryKeyConstraint('Session_id')
    )
    op.create_index('ix_Session_User_id', 'sessions', ['Session_User_id'], unique=False)
    op.create_table('images',
    sa.Column('Image_id', sa.UUID(), nullable=False),
    sa.Column('Uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('grad_cam_image_path', sa.String(), nullable=False),
    sa.Column('Image_Session_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['Image_Session_id'], ['sessions.Session_id'], ),
    sa.PrimaryKeyConstraint('Image_id')
    )
    op.create_index('ix_Image_Session_id', 'images', ['Image_Session_id'], unique=False)
    op.create_table('session_usage',
    sa.Column('Usage_id', sa.UUID(), nullable=False),
    sa.Column('Input_Tokens', sa.INTEGER(), nullable=True),
    sa.Column('Output_Tokens', sa.INTEGER(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Usage_Session_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['Usage_Session_id'], ['sessions.Session_id'], ),
    sa.PrimaryKeyConstraint('Usage_id'),
    sa.UniqueConstraint('Usage_Session_id')
    )
    op.create_table('user_features',
    sa.Column('Feature_id', sa.UUID(), nullable=False),
    sa.Column('User_Feature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('Feature_Session_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['Feature_Session_id'], ['sessions.Session_id'], ),
    sa.PrimaryKeyConstraint('Feature_id')
    )
    op.create_index('ix_Feature_Session_id', 'user_features', ['Feature_Session_id'], unique=False)
    op.create_table('prediction_result',
    sa.Column('Prediction_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prediction_value', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Prediction_Session_id', sa.UUID(), nullable=False),
    sa.Column('Prediction_Image_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['Prediction_Image_id'], ['images.Image_id'], ),
    sa.ForeignKeyConstraint(['Prediction_Session_id'], ['sessions.Session_id'], ),
    sa.PrimaryKeyConstraint('Prediction_id')
    )
    op.create_index('ix_Prediction_Image_id', 'prediction_result', ['Prediction_Image_id'], unique=False)
    op.create_index('ix_Prediction_Session_id', 'prediction_result', ['Prediction_Session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Prediction_Session_id', table_name='prediction_result')
    op.drop_index('ix_Prediction_Image_id', table_name='prediction_result')
    op.drop_table('prediction_result')
    op.drop_index('ix_Feature_Session_id', table_name='user_features')
    op.drop_table('user_features')
    op.drop_table('session_usage')
    op.drop_index('ix_Image_Session_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_Session_User_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_Full_Name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
