"""Add Nullable constraint for grad_cam_path column

Revision ID: 74a6769a07af
Revises: f6f202fc4836
Create Date: 2026-04-01 13:57:54.460729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74a6769a07af'
down_revision: Union[str, Sequence[str], None] = 'f6f202fc4836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'grad_cam_image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('prediction_result', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('prediction_result', 'Updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_result', sa.Column('Updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('prediction_result', 'created_at')
    op.alter_column('images', 'grad_cam_image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
