"""ADD Created at column to the user feature

Revision ID: f6f202fc4836
Revises: 07087dc0dd28
Create Date: 2026-03-27 15:43:35.988918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f202fc4836'
down_revision: Union[str, Sequence[str], None] = '07087dc0dd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_result', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prediction_result', 'prediction_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prediction_result', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prediction_result', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('user_features', sa.Column('Created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_Full_Name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Full_Name'), 'users', ['Full_Name'], unique=False)
    op.drop_column('user_features', 'Created_at')
    op.alter_column('prediction_result', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prediction_result', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('prediction_result', 'prediction_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('prediction_result', 'model_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
